quarkus:
  test:
    native-image-profile: test
    native-image-wait-time: 300
  vertx:
    prefer-native-transport: true
  grpc:
    server:
      host: 0.0.0.0
      test-port: 6566
      port: 6566
      instances: 1
      enable-reflection-service: true
  native:
    additional-build-args:
      - "-H:+PrintClassInitialization"
      - "-H:+ReportExceptionStackTraces"
      - "-H:GenerateDebugInfo=1"
      - "-H:+StackTrace"
  package:
    main-class: com.xabe.quarkus.grpc.App
  log:
    console:
      enable: true
      level: DEBUG
    category:
      com.xabe.quarkus:
        level: DEBUG
      io.quarkus:
        level: INFO
      io.quarkus.grpc:
        level: DEBUG
      io.grpc:
        level: INFO
      io.quarkus.vertx:
        level: DEBUG

  application:
    name: quarkus-grpc
  banner:
    enabled: false
  http:
    so-reuse-port: true
    test-port: 8009
    port: 8009
    root-path: /api
  ssl:
    native: false